AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "spec/**/*"

Style/ClassVars:
  Exclude:
    - "spec/**/*"
